### ISSUE TITLE
Many files acciendtally incldued creating conflicts with other packages

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/asv-feedstock#42]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

![image](https://github.com/conda-forge/asv-feedstock/assets/90008/91e1bb2c-31fc-47c8-8a2e-df9ff4fa235c)

The folders:

* `benchmarks`
* `docs`
* `test`

should not be included

### Installed packages

```shell
* conda-forge/linux-64::keras-3.3.3-pyhd8ed1ab_0
* conda-forge/linux-64::asv-0.6.3-py310hc6cd4ac_0

ClobberError: The package 'conda-forge/linux-64::asv-0.6.3-py310hc6cd4ac_0' cannot be installed due to a
path collision for 'lib/python3.10/site-packages/benchmarks/__init__.py'.
This path already exists in the target prefix, and it won't be removed by
an uninstall action in this transaction. The path appears to be coming from
the package 'conda-forge/noarch::keras-3.3.3-pyhd8ed1ab_0', which is already installed in the prefix.


ClobberError: The package 'conda-forge/linux-64::asv-0.6.3-py310hc6cd4ac_0' cannot be installed due to a
path collision for 'lib/python3.10/site-packages/benchmarks/__pycache__/__init__.cpython-310.pyc'.
This path already exists in the target prefix, and it won't be removed by
an uninstall action in this transaction. The path appears to be coming from
the package 'conda-forge/noarch::keras-3.3.3-pyhd8ed1ab_0', which is already installed in the prefix.
```

### Environment info

```shell
linux64
```

**Comment by saraedum** [comment]
Should we also create an issue in the keras feedstock?

I guess that's a bug upstream. I couldn't find an issue describing this, should we open one?

**Comment by hmaarrfk** [comment]
yes, also on the keras feedstock, i didn't really have time to open both.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
I guess we should also report upstream to asv. The same thing happens in their pypi release
![image](https://github.com/conda-forge/asv-feedstock/assets/90008/390db66e-de78-4d1f-84df-12d5b3a34ab3)
